// Copyright (c) Intangible Realities Laboratory. All rights reserved.
// Licensed under the GPL. See License.txt in the project root for license information.

#pragma kernel UploadIntArray

#include "Test.cginc"

StructuredBuffer<int> int_array;

[numthreads(1,1,1)]
void UploadIntArray ()
{
    assert_equal(0.0, int_array[0], __LINE__);
    assert_equal(1.0, int_array[1], __LINE__);
    assert_equal(2.0, int_array[2], __LINE__);
    assert_equal(3.0, int_array[3], __LINE__);
    assert_equal(4.0, int_array[4], __LINE__);
};