//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Simulation : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabSpace
        {
            get
            {
                return SteamVR_Actions.simulation_GrabSpace;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interact
        {
            get
            {
                return SteamVR_Actions.simulation_Interact;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.simulation_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean PauseMenu
        {
            get
            {
                return SteamVR_Actions.simulation_PauseMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean IncreaseInteractionStrength
        {
            get
            {
                return SteamVR_Actions.simulation_IncreaseInteractionStrength;
            }
        }
        
        public virtual SteamVR_Action_Boolean DecreaseInteractionStrength
        {
            get
            {
                return SteamVR_Actions.simulation_DecreaseInteractionStrength;
            }
        }
    }
}
