//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_Controller p_Controller;
        
        private static SteamVR_Input_ActionSet_UI p_UI;
        
        private static SteamVR_Input_ActionSet_Interactive p_Interactive;
        
        public static SteamVR_Input_ActionSet_Controller Controller
        {
            get
            {
                return SteamVR_Actions.p_Controller.GetCopy<SteamVR_Input_ActionSet_Controller>();
            }
        }
        
        public static SteamVR_Input_ActionSet_UI UI
        {
            get
            {
                return SteamVR_Actions.p_UI.GetCopy<SteamVR_Input_ActionSet_UI>();
            }
        }
        
        public static SteamVR_Input_ActionSet_Interactive Interactive
        {
            get
            {
                return SteamVR_Actions.p_Interactive.GetCopy<SteamVR_Input_ActionSet_Interactive>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_Controller = ((SteamVR_Input_ActionSet_Controller)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Controller>("/actions/Controller")));
            SteamVR_Actions.p_UI = ((SteamVR_Input_ActionSet_UI)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_UI>("/actions/UI")));
            SteamVR_Actions.p_Interactive = ((SteamVR_Input_ActionSet_Interactive)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Interactive>("/actions/Interactive")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.Controller,
                    SteamVR_Actions.UI,
                    SteamVR_Actions.Interactive};
        }
    }
}
