//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_Application p_Application;
        
        private static SteamVR_Input_ActionSet_Simulation p_Simulation;
        
        private static SteamVR_Input_ActionSet_FullScreenUI p_FullScreenUI;
        
        private static SteamVR_Input_ActionSet_InAppUI p_InAppUI;
        
        public static SteamVR_Input_ActionSet_Application Application
        {
            get
            {
                return SteamVR_Actions.p_Application.GetCopy<SteamVR_Input_ActionSet_Application>();
            }
        }
        
        public static SteamVR_Input_ActionSet_Simulation Simulation
        {
            get
            {
                return SteamVR_Actions.p_Simulation.GetCopy<SteamVR_Input_ActionSet_Simulation>();
            }
        }
        
        public static SteamVR_Input_ActionSet_FullScreenUI FullScreenUI
        {
            get
            {
                return SteamVR_Actions.p_FullScreenUI.GetCopy<SteamVR_Input_ActionSet_FullScreenUI>();
            }
        }
        
        public static SteamVR_Input_ActionSet_InAppUI InAppUI
        {
            get
            {
                return SteamVR_Actions.p_InAppUI.GetCopy<SteamVR_Input_ActionSet_InAppUI>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_Application = ((SteamVR_Input_ActionSet_Application)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Application>("/actions/Application")));
            SteamVR_Actions.p_Simulation = ((SteamVR_Input_ActionSet_Simulation)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Simulation>("/actions/Simulation")));
            SteamVR_Actions.p_FullScreenUI = ((SteamVR_Input_ActionSet_FullScreenUI)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_FullScreenUI>("/actions/FullScreenUI")));
            SteamVR_Actions.p_InAppUI = ((SteamVR_Input_ActionSet_InAppUI)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_InAppUI>("/actions/InAppUI")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.Application,
                    SteamVR_Actions.Simulation,
                    SteamVR_Actions.FullScreenUI,
                    SteamVR_Actions.InAppUI};
        }
    }
}
